### ISSUE TITLE
Navigation left to right

### ISSUE THREAD

**Issue by gpoontip** [piro0919/react-comic-viewer#124]
Currently it reads right to left.

Can we add a prop or setting to allow to read left to right?

**Comment by piro0919** [comment]
@gpoontip

Thank you for suggesting an nice idea. 😺 

I supported direction with props in version 0.3.0.
It would be helpful if you could upgrade the package and check it. 👍

**Comment by gpoontip** [comment]
@piro0919 thank you for implementing that feature so quickly!

I've upgraded and checked and it works great. One thing that I noticed however is that in mobile view, it starts from page 2 even if I have  initialCurrentPage={1} or if I don't use the  initialCurrentPage prop.

My particular example I'm using 8 pages

**Comment by piro0919** [comment]
@gpoontip 

Thank you for checking. 😸 

I have released a new version 0.3.2 that fixes all bugs.
Please use it by all means. 👍
