### ISSUE TITLE
Range slider is backwards when direction prop is "LTR"

### ISSUE THREAD

**Issue by gpoontip** [piro0919/react-comic-viewer#130]
**Describe the bug**
The "move" range slider is backwards when direction prop is set to "ltr"

**To Reproduce**
1. Set direction prop to "ltr"
2. Click on 'Move' button
3. See range slider is all the way to the right

**Expected behavior**
Range slider should start all the way to the left

**Comment by piro0919** [comment]
@gpoontip 

Thank you for your advice. 😄 

I made the fix in version 0.3.4.

It would be helpful if you could confirm it. 🙇

**Comment by gpoontip** [comment]
Works perfectly. Thanks for the swift updates. Great work on the library!
