### ISSUE TITLE
reset current page when changing pages

### ISSUE THREAD

**Issue by unknowingknow** [piro0919/react-comic-viewer#171]
First of all, thank you for your useful library.

**Is your feature request related to a problem? Please describe.**

There is a single page where I can switch between the comics displayed in the Viewer.
Since it is independent of the current page of the current comic, I want to switch the current page to 0 or any page when switching to another comic.

**Describe the solution you'd like**

- Creating a flag that can set the current page to `initialCurrentPage` when `pages` change
  - I'm not familiar with writing react so there may be a better way...

```
export type ComicViewerProps = {
...
  isResetCurrentPageWhenChangingPages?: boolean
};

function ComicViewer({...}: JSX.Element {
...
  useEffect( () => {
    if (isResetCurrentPageWhenChangingPages) {
      setCurrentPage( isSingleView ? initialCurrentPage : Math.floor(initialCurrentPage / 2) * 2)
    }
  }, [pages, initialCurrentPage, isSingleView])
...
}
```

**Describe alternatives you've considered**

I think there is a way to reload the window when switching another comic, but the UX is not good...

**Comment by piro0919** [comment]
@unknowingknow 

Thanks for your advice. 👍 
Do you want to initialize the page when you move to a new comic?

If so, `page props` allows `ReactNode` and I think it can be used. 👍 
https://github.com/piro0919/react-comic-viewer/blob/2688ba145b829988d5d5fa7d4e8851df3bae85bd/src/index.tsx#L54

If it's difficult to implement, feel free to ask again. 😺

**Comment by unknowingknow** [comment]
> Do you want to initialize the page when you move to a new comic?

I want to initialize the `currentPage`, which is the number of pages currently displayed. 
I'm sorry if I just don't understand. Is it possible to initialize `currentPage` by using `ReactNode`?

**Comment by piro0919** [comment]
@unknowingknow 

I'm sorry, but I still don't understand. 🙇 

How are you trying to switch to another comic? 🤔
If you have two arrays and you're trying to switch, I don't think you need to flag the package.

And of course I don't think it's necessary to reload the window. 👍

**Comment by unknowingknow** [comment]
For example, I have two Comics (let's say A and B) and I want to switch between them in one viewer.
The flow is as follows.

- First, set the `pages` of A to viewer and display from the initial value of `currentPage` 0.
- After finishing reading A (`currentPage` is the last page of A), switch to B.
- If I set `pages` of B to viewer, I want it to display from the initial `currentPage` 0, but it tries to display from the last page of A.

In this case, I will want to initialize `currentPage` at the time the `pages` are switched so It would be helpful if a feature was provided for this purpose. I used the flag because I thought there might be cases where you didn't want it to be initialized when `pages` were switched.

**Comment by piro0919** [comment]
@unknowingknow 

Thank you, I understand it completely. 👍 

In my opinion, when switching comics, if you apply re-render, it will behave as intended.
Please, try it. 👍 

example code: 
```
  const [n, setN] = useState(0);
  const v = [
    [
      "/comics/0.jpg",
      "/comics/1.jpg",
      "/comics/2.jpg",
      <div style={{ display: "flex", justifyContent: "flex-end" }}>
        <button
          onClick={() => {
            setN(1);
          }}
        >
          next
        </button>
      </div>,
    ],
    [
      "/comics/3.jpg",
      "/comics/4.jpg",
      <div style={{ display: "flex", justifyContent: "flex-end" }}>
        <button
          onClick={() => {
            setN(2);
          }}
        >
          next
        </button>
      </div>,
    ],
    ["/comics/5.jpg"],
  ];

  return (
    <Layout>
      <ComicViewer
        key={v[n][0] as string} // re-render flag
        pages={v[n]}
      />
  );
```

**Comment by unknowingknow** [comment]
Thank you very much. 🙇  
Works as expected.
