### ISSUE TITLE
CSS customization props

### ISSUE THREAD

**Issue by rishighan** [piro0919/react-comic-viewer#174]
**Is your feature request related to a problem? Please describe.**

This is a request to add some style-related props to the `ComicViewer` component. Currently, the styles are applied from the original CSS.

**Describe the solution you'd like**
Something like this would be nice:

```typescript
<ComicViewer
  pages="{extractedComicBook}"
  direction="ltr"
  containerBGColor="#CCC"
  leftArrowStyle={{border: "1px solid red"}}
  rightArrowStyle={{border: "1px solid green"}}
  ...
/>
```

**Describe alternatives you've considered**

I think the classnames for the container, anchor links for left and right navigation, and the actual image `div` are auto-generated and hence there is no reliable way to override them.

**Additional context**

My app actually opens the `ComicViewer` in a modal, so that the user can _glance_ at the comic and close the modal. I think there is tremendous value in allowing CSS customization of the component via props.

**Comment by rishighan** [comment]
Would you like to have me submit a PR?

**Comment by piro0919** [comment]
@rishighan 

Thanks for the nice idea!
And I'm sorry for the late reply.

I have released v0.4.0 of the package, and added `className` to props in this release.
Please check it out. 👍

**Comment by rishighan** [comment]
Thanks @piro0919 I will check it out!

**Comment by rishighan** [comment]
Sorry to bump this, but can you provide examples of usage?
